# -*- coding: utf-8 -*-
"""Copie de Gamma_Python_fundamentals_23_09_28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tRA4Kmj3LX7HxfJp0ZiVunM_Fw2_V43P

# WHILE LOOP
##How do you use while in Python?
A while loop is used to repeatedly execute the indented block of code as long as the True-False condition following the word 'while' evaluates to True. It is ideal for situations where the total number of iterations necessary cannot be defined beforehand, such as obtaining user input and checking it until correct input is entered.

##What is a while statement in Python?
The word 'while' in Python is a reserved word which creates a while loop using the syntax: while condition: do_stuff. If do_stuff is more than one line, it should be put on the next line and indented. The 'condition' is evaluated before each iteration of the loop, and 'do_stuff' is executed so long as 'condition' is true.

##What is a while loop Python?
A while loop has the syntax 'while condition: do_stuff' where 'do_stuff' is usually placed on the next line and indented. It executes the statements in 'do_stuff' repeatedly so long as 'condition' is true.
"""

# for loop print from 1 to 10
print("For loop")
for i in range(1,11):
  print(i)


# while loop print from 1 to 10
print("While loop")
i=1
while i<11:
  print(i)
  i=i+1 # i+=1 la même chose

def n_print(n,odd_or_even):
    i = 1
    while i<=n:
      if odd_or_even == "impair" and i%2!=0:
            print(i)
      elif odd_or_even == "pair" and i%2==0:
            print(i)
      i=i+1

n_print(19,"impair")


# we can stop the loop by adding a break keyword in a while or a for loop
# to prevent errors or infinite loops

def n_print(n,odd_or_even):
    i = 1
    while i<=n:
      if odd_or_even == "impair" and i%2!=0:
            print(i)
      elif odd_or_even == "pair" and i%2==0:
            print(i)
      elif odd_or_even != "pair" and odd_or_even != "impair":
        print("error in odd_or_event parameter")
        break
      i=i+1

n_print(19,"imopair")

"""## Rappel: Local and global variable"""

# i is define as a global variable and his value is 3
# i is used as a variable in the for loop and takes the value of range(5)
# The i in the for loop is a local variable
# The print statement will first look for a local i variable
# and if it doesn't exist it will look for a global one

# example 1 where the printed value is the local variable
i = 3
for i in range(5):
  print(i)


# example 2 where the printed value is the global variable
i = 3
for j in [0,True,0,i,"2",2,2,2]:
  print(i)

"""# Dictionary
## What is a dictionary?
Dictionaries are Python’s implementation of a data structure that is more generally known as an associative array. <br>
A dictionary consists of a collection of key-value pairs. Each key-value pair maps the key to its associated value.

## How do you define a dictionnary?
You can define a dictionary by enclosing a comma-separated list of key-value pairs in curly braces ({}).<br>
A colon (:) separates each key from its associated value:
"""

area_size = [11.25, 18.0, 20.0, 10.75, 9.50, 9.50]
area_name = ["hallway", "kitchen", "living room", "bedroom", "bathroom", "poolsize"]

# created a dictionary
dict_area = dict()
dict_area = {"hallway":11.25, "kitchen":18}
print(dict_area)
# return the value associated to kitchen
dict_area["kitchen"]

dict_area = {"Tarzs":[20, 20, 15], "Yasmine":[18,20]}
dict_area["Tarzs"][1]

dict_area = {"hallway":11.25, "kitchen":18}
dict_area

new_dict = dict()

# method 1
for i in range(len(area_name)):
  new_dict[area_name[i]]=area_size[i]



print(new_dict)

def lower_dict(new_dict):
  # transform the keys to a list and lowercase them
  key = new_dict.keys()
  key_list = list(key)
  lower_key_list = [unit_key.lower() for unit_key in key_list]

  # transform the values to a list
  value_list = list(new_dict.values())

  # key = list(new_dict.keys()).lower()
  # create a dictionary
  new_dict = dict()
  for i in range(len(value_list)):
    new_dict[lower_key_list[i]]=value_list[i]
  return new_dict

lower_dict({"Coco":2, "Banane":5, "Fraise":25})


def lower_dict(new_dict):
  # transform the keys to a list and lowercase them
  key_list = list(new_dict.keys)
  lower_key_list = [unit_key.lower() for unit_key in key_list]

  # transform the values to a list
  value_list = list(new_dict.values())

  # key = list(new_dict.keys()).lower()
  # create a dictionary
  new_dict = dict()
  for i in range(len(value_list)):
    new_dict[lower_key_list[i]]=value_list[i]
  return new_dict

type(dict_area.keys())

"""# Handle string like a list

Here we tried to interact with one string as if it was a list

"""

# Define a string variable 'name' with the value "Albert".
name = "Albert"

# Get the type of 'name' and print it.
type(name)

# Access and print the substring of 'name' from index 0 to 2 (inclusive of 0, exclusive of 3).
name[0:3]

"""# Tuple

## What is a tuple?
Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage.

## Why do we use them?
Tuples are used to store multiple items in a single variable.

## Technical assets
A tuple is a collection which is ordered and unchangeable.
## How are they represented?
Tuples are written with round brackets.
"""

# 1. Create a tuple 'x' with two elements (1, 2).
x = (1, 2)

# Print the tuple 'x'.
print(x)

# Get the type of 'x' and print it.
type(x)

# Access the first element of 'x' and print it.
x[0]

# Access the second element of 'x' and print it.
x[1]

# Create a tuple 'aire_rect' representing properties of a rectangle.
# It includes length, width, height, width, depth, depth, a boolean value, and a string.
aire_rect = (5, 10, 5, 5, 5, 5, True, "coucou")

# Assign the values of length 'l' and width 'L' from the 'aire_rect' tuple.
l, L = (5, 10)

# Print the length and width.
print("La longueur est", L)
print("La largeur est", l)

# 2. Write a Python function 'double_val_dic' that takes a dictionary as input and
# returns a new dictionary where all the values have been doubled.
def double_val_dic(dico):
    new_dict = {}
    for dict_item in dico.items():
        new_dict[dict_item[0]] = 2 * dict_item[1]
    return new_dict

# Example usage of 'double_val_dic' function.
double_val_dic({1: 1, 2: 2, 3: 3})

# Find the index of the first occurrence of 'True' in the 'aire_rect' tuple.
aire_rect.index(True)

"""## Set

"""

s = set()
s = {}

s1 = {2,4,5}
s2 = {2,6,9}
l = [2,2,2,2,4,5]
s_to_l = set(l)
print(l)
print(len(l))
print(s_to_l)
print(len(s_to_l))

s1.difference()

[('Marcus Garvey Park', ('Black', 'Cinnamon', 'Cleaning', None)),
 ('Highbridge Park',
  ('Gray',
   'Cinnamon',
   'Running, Eating',
   'Runs From, watches us in short tree')),
 ('Madison Square Park', ('Gray', None, 'Foraging', 'Indifferent')),
 ('City Hall Park', ('Gray', 'Cinnamon', 'Eating', 'Approaches')),
 ('J. Hood Wright Park', ('Gray', 'White', 'Running', 'Indifferent')),
 ('Seward Park', ('Gray', 'Cinnamon', 'Eating', 'Indifferent')),
 ('Union Square Park', ('Gray', 'Black', 'Climbing', None)),
 ('Tompkins Square Park', ('Gray', 'Gray', 'Lounging', 'Approaches'))]

"""# Boolean

## What is a Boolean?
Python boolean type is one of the built-in data types provided by Python, which represents one of the two values i.e. True or False.

##What do we use it for?
Generally, it is used to represent the truth values of the expressions. For example, 1==1 is True whereas 2<1 is False.

##Technical assets
The boolean value can be of two types only i.e. either True or False. The output <class ‘bool’> indicates the variable is a boolean data type.


###Tips
It will work exactly like the **WHERE** clause in SQL
"""

# Define a function named 'is_even' that takes an input 'number'.
def is_even(number):
    # Check if the 'number' is even by performing the modulus operation (% 2) and comparing it to 0.
    # If the result is 0, the number is even, and the function returns True. Otherwise, it returns False.
    return number % 2 == 0

# Call the 'is_even' function with the argument 2 and print the result.
print(is_even(2))

# Call the 'is_even' function with the argument 3 and print the result.
print(is_even(3))

"""# List

## What is a list?
Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.

##
Lists are used to store multiple items in a single variable.

Lists are created using square brackets:


"""

# the type is list
type([1,2,3,4,7])

# assign l to a list
l = [1,2,3,4,7,5]

# check what is the first value of l
l[0]

# let's change the 3rd value to 1
l[2] = 1
l

# let's see the value of the last element
l[-1]

# let's see all the elements before the last one
l[:-1]
l[0:-1] # Galaad

# let's see all the elements from the 3 position to the end
l[2:]


# let's reverse the order of the list l
l[::-1]

# let's take the 2 first elements and reverse the order
l[0:2][::-1]
l[0:2:-1] # doesn't work because first it reverse the list
l[0:2:-1]

# slice the list. Let's work only on the sub list from the 1st to the 3rd position
l[0:2] # Going from position 1 to position 2
l[0:3] # Going from position 1 to position 3
[l[0],l[3]] # Taking only values of position 1 and position 4

# Create a list with boolean, int, float and string
new_list = [True,1,2.5,"abc"]
new_list

# Create a list of a list

even_odd_list = [1,3,5,7,2,4,6]
even_odd_list = [[1,3,5,7],[2,4,6]]
# Retrieve the 2nd element of the 2nd list
even_odd_list[1][1]

new_list = [[1,3,5,7],[2,4,[1,3,5,7],[2,4,6],6],[2,4,6]]

l = [1,2,3,4,7]
new_l = l[2::-1]
new_l

hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
areas = ["hallway", hall, "kitchen", kit, "living room", liv,
         "bedroom", bed, "bathroom", bath]

areas[-4:]
areas[:-2]

"""## The methods


"""

new_list2 = [1,2,"e"]
print(new_list2)
# ajouter l'item "Hello"
new_list2.append("Hello")
print(new_list2)

# Enlever le dernier item ajouté dans la liste
new_list2.pop()
print(new_list2)

# To know the index, we use the index method
# I want to the position of "e"
new_list2.index("e")

# To remove one specific element
# Let's remove 1
new_list2.remove(1)
print(new_list2)

"""# Condition statement
With more than 2 options
"""

def surface_room(room_name):
 if room_name== "hallway" :
   res = hall
 elif room_name == "kitchen" :
   res = kit
 elif room_name == "living room" :
   res = liv
 elif room_name == "bathroom" :
   res = bath
 elif room_name == "bedroom" :
   res = bed
 else :
   res = "Try again with a correct room name"
 return res

print(surface_room("bedroom"))
print(surface_room("BEDROOM"))

"""# For LOOP"""

areas_name = ["hallway", "kitchen", "living room", "bedroom", "bathroom"]

def surface_room (room_name) :
  room_name = room_name.lower()
  if room_name =="hallway":
    result = hall
  elif room_name =="kitchen":
        result = kit
  elif room_name =="living room":
         result = liv
  elif room_name =="bathroom":
        result = bath
  elif room_name =="bedroom":
        result = bed
  else :
      result ="Try again with a correst room name"
  return result

surface_room("hall")
surface_room("kit")
surface_room("liv")

#for i in areas_name:
#  print(i,": ", surface_room(i))


for i in range(len(areas_name)):
  print(surface_room(areas_name[i]))

"""## List Comprhension"""

surface_list =[]
for i in areas_name:
  surface_list.append(surface_room(i))

# list comprehension
print([surface_room(room) for room in areas_name])

# add a condition
print(areas_name)
[surface_room(room) for room in areas_name if len(room)<10 and len(room)>7]

max = list[0]
max