# -*- coding: utf-8 -*-
"""Activity 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIu4kzJpApAcBKLsDKPRKFDXN6M2ySaj
"""

# 27_09_23 If & functions :

# Activity 1:
# Let's write a function called is_even() that takes a number as input and returns
# True if the number is even, and False otherwise.

def is_even(number):
    """
    Check if a number is even.

    Parameters:
    number (int): The number to check.

    Returns:
    bool: True if the number is even, False otherwise.
    """
    if number % 2 == 0:
        return True
    else:
        return False

# Activity 2:

# 1. We will create a list named areas, which contains the area of the hallway (hall),
# kitchen (kit), living room (liv), bedroom (bed), and bathroom (bath), in that order.
# We use the predefined variables:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# 1 and 2 Let's display the areas using the print() function:
areas = [hall, kit, liv, bed, bath]
print(areas)

# 3 and 4 Complete the code that creates the list of areas.
# Build the list so that it contains the name of each room as a string first,
# then its area. In other words, add the strings "hallway", "kitchen", and "bedroom"
# at the appropriate positions. Display areas using the print() function.
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]
print(areas)

# 5. Let's create a variable house that is a list of lists consisting of rooms and areas:
house = [["hallway", hall], ["kitchen", kit], ["living room", liv], ["bedroom", bed], ["bathroom", bath]]

# 6. Display the second element of areas:
print(areas[1])

# 7. Display the last element of areas:
print(areas[9])
# or
print(areas[-1])

# 8. Display the last 4 elements of areas using negative numbers:
print(areas[-4:])

# 9. Display the area of the living room:
print(areas[5])

# 10. Create a new variable, eat_sleep_area, which contains the sum of
# the kitchen area and the bedroom area. Print the variable:
eat_sleep_area = house[1][1] + house[3][1]
print(eat_sleep_area)

# 11. Create the function surface_room that shows the area when you input
# the name of the room. If the name does not match an existing room name, write:
# "Try again with a correct room name"

hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

def surface_room(room_name):
    """
    Get the area of a room by providing its name.

    Parameters:
    room_name (str): The name of the room.

    Returns:
    float or str: The area of the room if it exists, otherwise an error message.
    """
    if room_name == "hallway":
        res = hall
    elif room_name == "kitchen":
        res = kit
    elif room_name == "living room":
        res = liv
    elif room_name == "bathroom":
        res = bath
    elif room_name == "bedroom":
        res = bed
    else:
        res = "Try again with a correct room name"
    return res