# -*- coding: utf-8 -*-
"""Course 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MjySVjQJTbECzAjfBLc6jaDE_233wXS

# How to write code?
"""

# Comments start with "#"

# Int (Integer): Used to store whole numbers, such as:
integer = 2

# Float (Floating-point number): Used to store decimal numbers, such as:
floating = 2.4

# String: Used to store text, enclosed in quotes, like:
text = "hello"

# Boolean: Used for logical operations and comparisons, with values True or False.
true_value = True
false_value = False

# These data types are the basic building blocks you'll frequently use in programming to represent different information and perform various operations.

"""## Using print will display the result of the calculation even if it's not the last line written.

"""

# Example of print with Integers
print(2 + 2)

# Example of print with strings
print("Hello World")

"""## Not using the print() function will only display the last line.

"""

2+2
"Hello World"

"""
# Data types must be respected."""

# What's happening?
print(2 + "2")
# Error: Because data types do not match.

# When you run this code without the print() function, you will only see the result of the last operation, which is the error generated by the line "print(2 + "2")".
# This error occurs because you are trying to add an integer (2) with a string ("2"), which is not a valid operation in Python.

"""
# Concatenation"""

# If we add 2 string-type data, it will concatenate them
print("2" + "2")
# Concatenate 2 strings

print("My name is" + " " + "Gamma")
# Concatenate 2 strings to form a sentence

"""
## Variables
# Note: Python distinguishes between uppercase and lowercase letters. Therefore, 'TRUE' is not equivalent to 'True'."""

x = 1
print(x)

"""# Fonctions
## Les fonctions sont des scripts écrits pour effectuer une tâche spécifique.
"""

# In a sentence, my function will return an age and a name
def age_name(age, name):
  """
    Concatenates age and name into a descriptive sentence.

    Parameters:
    age (int): The individual's age.
    name (str): The individual's name.

    Returns:
    str: A descriptive sentence containing the individual's age and name.
    """
    # The function takes two arguments, age and name, and concatenates them to form a descriptive sentence
    res = "I am " + str(age) + " years old and my name is " + str(name)
    return res

# Calling the function with specific values for age and name
print(age_name(23, "Yamine"))

# Calling the function by reversing the order of the arguments name and age
age_name(name="Yamine", age=23)

"""
##Local and Global Variables and How to Define a Function

#Global variables are those defined outside of functions. They are the first value checked outside of a function. Local variables are those defined inside a function. They are the first value within the function where they were defined.
"""

# res = 0 is the global variable
# It will show this assignment to res
# Variable names inside the function don't matter
res = 0

def add_1(var_int):
    """
    Adds 5 to the input variable var_int.

    Parameters:
    var_int (int): Numeric value to which 5 will be added.

    Returns:
    int: Result of adding var_int and 5.
    """
    # A local variable res is defined inside the function
    res = var_int + 5
    return res

add_1(0)

def add_1(var_int=0):
    """
    Returns 5, regardless of the input value.

    Parameters:
    var_int (int, optional): Numeric value not used in this function. Defaults to 0.

    Returns:
    int: Constant value 5.
    """
    # Another add_1 function with a default argument var_int=0
    # A local variable res is defined inside the function
    res = 0 + 5
    return 5

# The global variable res remains unchanged
res

result = 0

def add_1(var_int):
    """
    Adds 1 to the input variable var_int.

    Parameters:
    var_int (int): Numeric value to which 1 will be added.

    Returns:
    int: Result of adding var_int and 1.
    """
    # A local variable result is defined inside the function
    result = var_int + 1
    return result

add_1(1)

"""
##Conditional Statement
"""

# If _cdn1_ is true:
#    _action1_
# Else:
#    _action2_

age = 16
if age < 18:
    # If the age is less than 18, the result is "minor"
    res = "minor"
else:
    # Otherwise, the result is "major"
    res = "major"

print(res)

# Currency conversion based on the choice of currency

def euro_dollars(amount_euros):
    """
    Converts an amount in euros to dollars.

    Parameters:
    amount_euros (float): Amount in euros to convert.

    Returns:
    float: Amount converted to dollars.
    """
    # This function converts an amount in euros to dollars
    final_amount = amount_euros * 1.06
    return final_amount

def dollars_euro(dollar):
    """
    Converts an amount in dollars to euros.

    Parameters:
    dollar (float): Amount in dollars to convert.

    Returns:
    float: Amount converted to euros.
    """
    # This function converts an amount in dollars to euros
    return dollar * 0.84

def convert_dollar_euro(amount, is_dollar=True):
    """
    Converts an amount to euros or dollars based on the is_dollar parameter.

    Parameters:
    amount (float): Amount to convert.
    is_dollar (bool): If True, converts to euros; otherwise, converts to dollars.

    Returns:
    float: Converted amount.
    """
    if is_dollar:
        # If is_dollar is True, conversion is from dollars to euros
        res = dollars_euro(amount)
    else:
        # Otherwise, conversion is from euros to dollars
        res = euro_dollars(amount)
    return res

print(convert_dollar_euro(3))
print(convert_dollar_euro(3, False))

"""
##How to Use a Function"""

# The round function only works with numbers
# If you try to use it with strings ("ok" and "okokok" in this example),
# it will result in an error.

round("ok", "okokok")

# The len function (which calculates length) only works with strings.
# Trying to use it with a number (324 in this example) will also result in an error.

len(324)

# minimum
# The min() function returns the minimum value among the given arguments.
min(3, 4, 5, 2, 5)

# maximum
# The max() function returns the maximum value among the given arguments.
max(3, 4, 5, 2, 5)

# count the number of characters
# The len() function returns the length of a string, i.e., the number of characters it contains.
len("hello, how are you?")

# To convert to a string
# The str() function converts a number or another type of data into a string.
str(9)

# To convert to an integer
# The int() function converts a string to an integer.
int("9")

# Adding a docstring to a function
# You can add a docstring (documentation string) to a function using triple quotes.
# This documentation explains the use of the function, the arguments it takes, and their meanings.
def convert_dollar_euro(amount, is_dollar=True):
 """
    Converts an amount between dollars and euros based on the is_dollar parameter.

    Parameters:
    amount (float): The amount to convert.
    is_dollar (bool, optional): The currency of the amount to convert. If True, the amount is in dollars and will be converted to euros. If False, the amount is in euros and will be converted to dollars. Defaults to True.

    Returns:
    float: The converted amount.
    """
    if is_dollar:
        res = dollars_euro(amount)
    else:
        res = euro_dollars(amount)
    return res

# You can use the help() function to display the documentation of a function.
help(convert_dollar_euro)